name: build-push
on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        type: string
      MAKE_TARGET:
        type: string
        default: 'ci-cd-build'
      VERSION:
        type: string
      DOCKER_IDENTIFIER:
        type: string
      DOCKER_REG:
        type: string
      DOCKER_FILE_NAME:
        type: string
        default: 'Dockerfile'
      APP_NAME_VAR:
        type: string
        default: 'APP_NAME'
    secrets:
      GKE_SA_KEY:
        required: true
env:
  TOKEN: ${{ secrets.GITPAT }}
  DOCKER_REPO: ${{ vars.DOCKER_REPO }}

  ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
  DOCKER_REG: ${{ inputs.DOCKER_REG }}
  VERSION: ${{ inputs.VERSION }}
  DOCKER_IDENTIFIER: ${{ inputs.DOCKER_IDENTIFIER }}

jobs:

  build:
    runs-on: zk-self-hosted
    environment:
      name: ${{ inputs.ENVIRONMENT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure git for private modules
        run: git config --global url."https://$TOKEN:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Build
        run: |
          make ${{ inputs.MAKE_TARGET }}

  docker-push:
    needs: build
    runs-on: zk-self-hosted
    env:
      REPO_NAME: ${{ format('{0}/{1}/{2}/{3}', inputs.DOCKER_REG, vars.DOCKER_REPO, inputs.DOCKER_IDENTIFIER, vars[format('{0}', inputs.APP_NAME_VAR)] ) }}
      CREATE_REPO_NAME: ${{ format('{0}/{1}/{2}', vars.DOCKER_REPO, inputs.DOCKER_IDENTIFIER, vars[format('{0}', inputs.APP_NAME_VAR)] ) }}
    environment:
      name: ${{ inputs.ENVIRONMENT }}
    steps:
      - name: Authenticate to Google Cloud
        if: ${{ vars.DOCKER_REG_CURRENT_CLOUD == 'gcp' }}
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: Docker build
        run: |-
          docker build -f ${{ inputs.DOCKER_FILE_NAME }} --tag "$REPO_NAME:$GITHUB_SHA" .

      - name: Docker Tag
        run: |-
          docker tag "${REPO_NAME}:${GITHUB_SHA}" "${REPO_NAME}:${VERSION}"

      - name: Docker push
        run: |-
          docker image push "${REPO_NAME}:${GITHUB_SHA}"
          docker image push "${REPO_NAME}:${VERSION}"
