name: build-push
on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        type: string
      MAKE_TARGET:
        type: string
        default: 'ci-cd-build'
      VERSION:
        type: string
      DOCKER_IDENTIFIER:
        type: string
      PROJECT_ID:
        type: string
      DOCKER_FILE_NAME:
        type: string
        default: 'Dockerfile'
      APP_NAME_VAR:
        type: string
        default: 'APP_NAME'
    secrets:
      GKE_SA_KEY:
        required: true
env:
  TOKEN: ${{ secrets.GITPAT }}
  ENVIRONMENT: ${{ inputs.ENVIRONMENT }}


  GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}
  DOCKER_REG: ${{ vars.DOCKER_REG }}
  PROJECT_ID: ${{ inputs.PROJECT_ID }}
  DOCKER_REPO: ${{ vars.DOCKER_REPO }}
  APP_NAME: ${{ inputs.APP_NAME }}
  VERSION: ${{ inputs.VERSION }}
  DOCKER_IDENTIFIER: ${{ inputs.DOCKER_IDENTIFIER }}

jobs:

  print-envs:
    runs-on: zk-self-hosted
    environment:
      name: ${{ inputs.ENVIRONMENT }}
    steps:
      - name: Check output
        run: |
          echo "GIT_TAG=$GIT_TAG"
          echo "DOCKER_TAG=$VERSION"
          echo "GITHUB_SHA=$GITHUB_SHA"
          echo "DOCKER_REPO=$DOCKER_REPO"
          echo "ENVIRONMENT=$ENVIRONMENT"
          echo "PROJECT_ID=$PROJECT_ID"

  app-build:
    runs-on: zk-self-hosted
    env:
      APP_NAME: ${{ vars[format('{0}', inputs.APP_NAME_VAR)] }}
    environment:
      name: ${{ inputs.ENVIRONMENT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure git for private modules
        run: git config --global url."https://$TOKEN:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Build
        run: |
          make ${{ inputs.MAKE_TARGET }}

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: login to docker registry
        run: |
          gcloud auth configure-docker $DOCKER_REG --quiet

      - name: Docker build
        run: |-
          docker build -f ${{ inputs.DOCKER_FILE_NAME }} --tag "$DOCKER_REG/$PROJECT_ID/$DOCKER_REPO/$DOCKER_IDENTIFIER/$APP_NAME:$GITHUB_SHA" .

      - name: Docker Tag
        run: |-
          docker tag "$DOCKER_REG/$PROJECT_ID/$DOCKER_REPO/$DOCKER_IDENTIFIER/$APP_NAME:$GITHUB_SHA" "$DOCKER_REG/$PROJECT_ID/$DOCKER_REPO/$DOCKER_IDENTIFIER/$APP_NAME:$VERSION"

      - name: Docker push
        run: |-
          docker push "$DOCKER_REG/$PROJECT_ID/$DOCKER_REPO/$DOCKER_IDENTIFIER/$APP_NAME:$GITHUB_SHA"
          docker push "$DOCKER_REG/$PROJECT_ID/$DOCKER_REPO/$DOCKER_IDENTIFIER/$APP_NAME:$VERSION"
