name: copy-secret
on:
  workflow_call:
    inputs:
      CLUSTERNAME:
        type: string
        required: true
      FROM_NAMESPACE:
        type: string
        required: true
      ENVIRONMENT:
        type: string
        required: true
      TO_NAMESPACE:
        type: string
        required: true
      SECRET_NAME:
        type: string
        required: true
    secrets:
      GKE_SA_KEY:
        required: true
env:
  CLUSTERNAME: ${{ inputs.CLUSTERNAME }}
  FROM_NAMESPACE: ${{ inputs.FROM_NAMESPACE }}
  TO_NAMESPACE: ${{ inputs.TO_NAMESPACE }}
  SECRET_NAME: ${{ inputs.SECRET_NAME }}
  GKE_ZONE: ${{ vars.GKE_ZONE }}

jobs:
  deploy:
    env:
      GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}
    environment:
      name: ${{ inputs.ENVIRONMENT }}
    runs-on: zk-self-hosted
    steps:
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ env.GKE_SA_KEY }}'

      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: '${{ env.CLUSTERNAME }}'
          location: '${{ env.GKE_ZONE }}'

      - name: copy ${{ env.FROM_NAMESPACE }} ${{ env.SECRET_NAME }} to ${{ env.TO_NAMESPACE }}
        run: |-
          kubectl create namespace $TO_NAMESPACE --dry-run=client -o yaml | kubectl apply -f -
          kubectl -n $FROM_NAMESPACE get secret $SECRET_NAME -o yaml | yq 'del(.metadata.creationTimestamp, .metadata.uid, .metadata.resourceVersion, .metadata.namespace)' | kubectl apply --namespace $TO_NAMESPACE  -f -
