name: docker-build-push
on:
  workflow_call:
    inputs:
      VERSION:
        type: string
      ENVIRONMENT:
        type: string
      DOCKER_IDENTIFIER:
        type: string
      PROJECT_ID:
        type: string
      DOCKER_FILE_NAME:
        type: string
        default: 'Dockerfile'
      ARTIFACT_NAME:
        type: string
        default: 'build-artifacts'
      APP_NAME:
        type: string
    secrets:
      GKE_SA_KEY:
        required: true
env:
  GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}
  DOCKER_REG: ${{ vars.DOCKER_REG }}
  PROJECT_ID: ${{ inputs.PROJECT_ID }}
  DOCKER_REPO: ${{ vars.DOCKER_REPO }}
  APP_NAME: ${{ inputs.APP_NAME }}
  VERSION: ${{ inputs.VERSION }}
  DOCKER_IDENTIFIER: ${{ inputs.DOCKER_IDENTIFIER }}

jobs:

  docker-build:
    environment:
      name: ${{ inputs.ENVIRONMENT }}
    runs-on: zk-self-hosted
    steps:
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ env.GKE_SA_KEY }}'

      - name: login to docker registry
        run: |
          gcloud auth configure-docker $DOCKER_REG --quiet

      - uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.ARTIFACT_NAME }}

      - name: Docker build
        run: |-
          echo "DOCKER_TAG=$VERSION"
          docker build -f ${{ inputs.DOCKER_FILE_NAME }} --tag "$DOCKER_REG/$PROJECT_ID/$DOCKER_REPO/$DOCKER_IDENTIFIER/$APP_NAME:$GITHUB_SHA" .

      - name: Docker Tag
        run: |-
          echo "DOCKER_TAG=$VERSION"
          docker tag "$DOCKER_REG/$PROJECT_ID/$DOCKER_REPO/$DOCKER_IDENTIFIER/$APP_NAME:$GITHUB_SHA" "$DOCKER_REG/$PROJECT_ID/$DOCKER_REPO/$DOCKER_IDENTIFIER/$APP_NAME:$VERSION"

      - name: Docker push
        run: |-
          echo "DOCKER_TAG=$VERSION"
          docker push "$DOCKER_REG/$PROJECT_ID/$DOCKER_REPO/$DOCKER_IDENTIFIER/$APP_NAME:$GITHUB_SHA"
          docker push "$DOCKER_REG/$PROJECT_ID/$DOCKER_REPO/$DOCKER_IDENTIFIER/$APP_NAME:$VERSION"
