name: deploy
on:
  workflow_call:
    inputs:
      CLUSTERNAME:
        type: string
        required: true
      VERSION:
        type: string
        required: true
      MIGRATION_VERSION:
        type: string
      PROJECT_ID:
        type: string
        required: true
      ENVIRONMENT:
        type: string
        required: true
      ZK_CLOUD_DOMAIN:
        type: string
        description: 'Zk cloud domain'
    secrets:
      GKE_SA_KEY:
        required: true
env:
  CLUSTERNAME: ${{ inputs.GKE_CLUSTER }}
  PROJECT_ID: ${{ inputs.PROJECT_ID }}
  ZK_CLOUD_DOMAIN: ${{ inputs.ZK_CLOUD_DOMAIN }}
  NAMESPACE: ${{ vars.NS }}
  GKE_ZONE: ${{ vars.GKE_ZONE }}
  ZK_INIT_CONTAINER_REPO: ${{ vars.ZK_INIT_CONTAINER_REPO }}
  ZK_INIT_CONTAINER_TAG: ${{ vars.ZK_INIT_CONTAINER_TAG }}

  GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}
  DOCKER_REG: ${{ vars.DOCKER_REG }}
  DOCKER_REPO: ${{ vars.DOCKER_REPO }}
  APP_NAME: ${{ vars.APP_NAME }}
jobs:
  deploy:
    env:
      CLUSTERNAME: ${{ inputs.CLUSTERNAME }}
      VERSION: ${{ inputs.VERSION }}
      MIGRATION_VERSION: ${{ inputs.MIGRATION_VERSION }}
      PROJECT_ID: ${{ inputs.PROJECT_ID }}
    environment:
      name: ${{ inputs.ENVIRONMENT }}
    runs-on: zk-self-hosted
    steps:
      - name: print-debug-vars
        run: |
          echo "VERSION=$VERSION"
          echo "MIGRATION_VERSION=MIGRATION_VERSION"
          echo "DOCKER_REG=$DOCKER_REG"
          echo "PROJECT_ID=$PROJECT_ID"
          echo "DOCKER_REPO=$DOCKER_REPO"
          echo "CLUSTERNAME=$CLUSTERNAME"
          echo "ZK_CLOUD_DOMAIN=$ZK_CLOUD_DOMAIN"
          echo "ZK_INIT_CONTAINER_REPO=$ZK_INIT_CONTAINER_REPO"
          echo "ZK_INIT_CONTAINER_TAG=$ZK_INIT_CONTAINER_TAG"

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ env.GKE_SA_KEY }}'

      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: '${{ env.CLUSTERNAME }}'
          location: '${{ env.GKE_ZONE }}'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        run: |-
          helm --install  \
          --set=image.tag=$VERSION \
          --set=image.migrationTag=$MIGRATION_VERSION \
          --set=global.dockerBase=$DOCKER_REG/$PROJECT_ID/$DOCKER_REPO/$CLUSTERNAME \
          --set=global.zkcloud.host=$ZK_CLOUD_DOMAIN \
          --set=global.zkInitContainer.repo=$ZK_INIT_CONTAINER_REPO \
          --set=global.zkInitContainer.tag=$ZK_INIT_CONTAINER_TAG \
          upgrade $APP_NAME \
           -f ./helm-charts/values.yaml ./helm-charts/ \
           --create-namespace \
           --namespace $NAMESPACE
