name: deploy
on:
  workflow_call:
    inputs:
      CLUSTERNAME:
        type: string
        required: true
      VERSION:
        type: string
        required: true
      MIGRATION_VERSION:
        type: string
      PROJECT_ID:
        type: string
        required: true
      ENVIRONMENT:
        type: string
        required: true
      ZK_CLOUD_DOMAIN:
        type: string
        description: 'Zk cloud domain'
      NAMESPACE_VAR:
        type: string
        default: 'NAMESPACE'
      APP_NAME_VAR:
        type: string
        default: 'APP_NAME'
      HELM_ARGS:
        type: string
    secrets:
      GKE_SA_KEY:
        required: true
env:
  CLUSTERNAME: ${{ inputs.CLUSTERNAME }}
  PROJECT_ID: ${{ inputs.PROJECT_ID }}
  VERSION: ${{ inputs.VERSION }}
  APP_NAME_VAR: ${{ inputs.APP_NAME_VAR }}
  MIGRATION_VERSION: ${{ inputs.MIGRATION_VERSION }}
  ZK_CLOUD_DOMAIN: ${{ inputs.ZK_CLOUD_DOMAIN }}
  HELM_ARGS: ${{ inputs.HELM_ARGS }}
  GKE_ZONE: ${{ vars.GKE_ZONE }}
  DOCKER_REG: ${{ vars.DOCKER_REG }}
  DOCKER_REPO: ${{ vars.DOCKER_REPO }}
jobs:
  deploy:
    env:
      GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}
      NAMESPACE: ${{ vars[format('{0}', inputs.NAMESPACE_VAR)] }}
      APP_NAME: ${{ vars[format('{0}', inputs.APP_NAME_VAR)] }}
    environment:
      name: ${{ inputs.ENVIRONMENT }}
    runs-on: zk-self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ env.GKE_SA_KEY }}'

      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: '${{ env.CLUSTERNAME }}'
          location: '${{ env.GKE_ZONE }}'

      - name: Deploy
        run: |-
          helm --install  \
          $HELM_ARGS \
          --set=image.tag=$VERSION \
          --set=image.migrationTag=$MIGRATION_VERSION \
          --set=global.dockerBase=$DOCKER_REG/$PROJECT_ID/$DOCKER_REPO/$CLUSTERNAME \
          --set=global.zkcloud.host=$ZK_CLOUD_DOMAIN \
          upgrade $APP_NAME \
           -f ./helm-charts/values.yaml ./helm-charts/ \
           --create-namespace \
           --namespace $NAMESPACE
