name: build-push
on:
  workflow_call:
    inputs:
      VERSION:
        type: string
        default: 'latest'
      DOCKER_IDENTIFIER:
        type: string
        default: 'prod'
      PROJECT_ID:
        type: string
        required: true
      DOCKER_REG:
        type: string
        required: true
      DOCKER_REPO:
        type: string
        required: true
      APP_NAME:
        type: string
        required: true
    secrets:
      GKE_SA_KEY:
        required: true
env:
  GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}
  DOCKER_REG: ${{ inputs.DOCKER_REG }}
  PROJECT_ID: ${{ inputs.PROJECT_ID }}
  DOCKER_REPO: ${{ inputs.DOCKER_REPO }}
  APP_NAME: ${{ inputs.APP_NAME }}
  VERSION: ${{ inputs.VERSION }}
  DOCKER_IDENTIFIER: ${{ inputs.DOCKER_IDENTIFIER }}

jobs:

  docker-build:
    runs-on: zk-self-hosted
    steps:
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ env.GKE_SA_KEY }}'

      - name: login to docker registry
        run: |
          gcloud auth configure-docker $DOCKER_REG --quiet

      - uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      - name: Docker build
        run: |-
          docker build  --tag "$DOCKER_REG/$PROJECT_ID/$DOCKER_REPO/$DOCKER_IDENTIFIER/$APP_NAME:$GITHUB_SHA" .

      - name: Docker Tag
        run: |-
          docker tag "$DOCKER_REG/$PROJECT_ID/$DOCKER_REPO/$DOCKER_IDENTIFIER/$APP_NAME:$GITHUB_SHA" "$DOCKER_REG/$PROJECT_ID/$DOCKER_REPO/$DOCKER_IDENTIFIER/$APP_NAME:$VERSION"

      - name: Docker push
        run: |-
          docker push "$DOCKER_REG/$PROJECT_ID/$DOCKER_REPO/$DOCKER_IDENTIFIER/$APP_NAME:$GITHUB_SHA"
          docker push "$DOCKER_REG/$PROJECT_ID/$DOCKER_REPO/$DOCKER_IDENTIFIER/$APP_NAME:$VERSION"
