name: deploy
on:
  workflow_call:
    inputs:
      CLUSTERNAME:
        type: string
        required: true
      VERSION:
        type: string
        required: true
      MIGRATION_VERSION:
        type: string
      PROJECT_ID:
        type: string
        required: true
      ENVIRONMENT:
        type: string
        required: true
      NAMESPACE_VAR:
        type: string
        default: 'NAMESPACE'
      APP_NAME_VAR:
        type: string
        default: 'APP_NAME'
      HELM_ARGS:
        type: string
        default: ''
    secrets:
      GKE_SA_KEY:
        required: true
      HELM_SECRETS_ARGS:
        required: false
env:
  CLUSTERNAME: ${{ inputs.CLUSTERNAME }}
  PROJECT_ID: ${{ inputs.PROJECT_ID }}
  VERSION: ${{ inputs.VERSION }}
  APP_NAME_VAR: ${{ inputs.APP_NAME_VAR }}
  MIGRATION_VERSION: ${{ inputs.MIGRATION_VERSION }}
  ZK_CLOUD_DOMAIN: ${{ vars.ZK_CLOUD_DOMAIN }}
  HELM_ARGS: ${{ inputs.HELM_ARGS }}
  HELM_SECRETS_ARGS: ${{ secrets.HELM_SECRETS_ARGS }}
  GKE_ZONE: ${{ vars.GKE_ZONE }}
  DOCKER_REG: ${{ vars.DOCKER_REG }}
  DOCKER_REPO: ${{ vars.DOCKER_REPO }}
jobs:
  predeploy:
    environment:
      name: ${{ inputs.ENVIRONMENT }}
    runs-on: zk-self-hosted
    outputs:
      RESOLVED_ZONE: ${{ steps.extractZone.outputs.RESOLVED_ZONE }}
    steps:
      - name: Extract zone
        id: extractZone
        env:
          OVERRIDE_ZONE: ${{ vars[format('{0}_ZONE', inputs.CLUSTERNAME)] }}
        run: |
          echo "OVERRIDE_ZONE=$OVERRIDE_ZONE"
          if [[ -z $OVERRIDE_ZONE ]]
          then
            echo "RESOLVED_ZONE=$GKE_ZONE" >> $GITHUB_OUTPUT
            echo "resolvedzone1=$GKE_ZONE"
          else
            echo "RESOLVED_ZONE=$OVERRIDE_ZONE" >> $GITHUB_OUTPUT
            echo "resolvedzone0=$OVERRIDE_ZONE"
          fi
          

  deploy:
    needs: predeploy
    env:
      GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}
      NAMESPACE: ${{ vars[format('{0}', inputs.NAMESPACE_VAR)] }}
      APP_NAME: ${{ vars[format('{0}', inputs.APP_NAME_VAR)] }}
      GKE_ZONE: ${{ needs.predeploy.outputs.RESOLVED_ZONE }}
    environment:
      name: ${{ inputs.ENVIRONMENT }}
    runs-on: zk-self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ env.GKE_SA_KEY }}'

      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: '${{ env.CLUSTERNAME }}'
          location: '${{ env.GKE_ZONE }}'

      - name: Deploy
        env:
          CLOUD_DOMAIN: ${{ vars[format('{0}_CLOUD', env.CLUSTERNAME)] }}
        run: |-
          echo "CLOUD_DOMAIN=$CLOUD_DOMAIN"
          helm dependency update ./helm-charts
          helm --install  \
          $HELM_ARGS \
          $HELM_SECRETS_ARGS \
          --set=image.tag=$VERSION \
          --set=image.migrationTag=$MIGRATION_VERSION \
          --set=global.dockerBase=$DOCKER_REG/$PROJECT_ID/$DOCKER_REPO/$CLUSTERNAME \
          --set=global.zkcloud.host=$ZK_CLOUD_DOMAIN \
          upgrade $APP_NAME \
           -f ./helm-charts/values.yaml ./helm-charts/ \
           --create-namespace \
           --namespace $NAMESPACE
