name: env_test
on:
  workflow_call:
jobs:
  init:
    runs-on: zk-self-hosted
    environment: poc
    steps:
      - name: Extract cluster and version
        id: extractClusterAndVersion
        run: |
          echo "APP_NAME=${{ vars.APP_NAME }} "
          
