# Common action: to be called by other actions
name: helm-publish
on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        type: string
      ARTIFACT_FOLDER_NAME:
        type: string
      MAKE_TARGET:
        type: string
        default: 'ci-cd-artifact'
      VERSION:
        type: string
      TARGET_FOLDER_NAME:
        type: string
        default: ''
    secrets:
      AWS_ACCESS_ID:
        required: true
      AWS_SECRET_KEY:
        required: true
jobs:
  file-publish:
    runs-on: zk-self-hosted
    environment:
      name: ${{ inputs.ENVIRONMENT }}
    env:
      ARTIFACT_FOLDER_NAME: ${{ inputs.ARTIFACT_FOLDER_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Build
        env:
          VERSION: ${{ inputs.VERSION }}
          ARTIFACT_FOLDER_NAME: ${{ inputs.ARTIFACT_FOLDER_NAME }}
        run: |-
          echo "VERSION from common action=${{ inputs.VERSION }}"
          make ${{ inputs.MAKE_TARGET }}

      - name: sync to S3
        run: |-
          aws s3 cp ${{ inputs.ARTIFACT_FOLDER_NAME }} ${{ vars.FILE_BUCKET_NAME }}/${{ vars.S3_FOLDER_NAME }}/${{ inputs.TARGET_FOLDER_NAME }} --recursive --include "*"

      - name: Clear CF Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ vars.FILES_CF_DIST_ID }} --paths "/*"

     
