name: prod-init
on:
  workflow_call:
    inputs:
      GIT_TAG:
        type: string
      DOCKER_TAG:
        type: string
      ENVIRONMENT:
        type: string
env:
  GIT_TAG: ${{ inputs.GIT_TAG }}
  ENV: ${{ inputs.ENVIRONMENT }}
  DOCKER_TAG: ${{ inputs.DOCKER_TAG }}

jobs:
  init:
    runs-on: zk-self-hosted
    outputs:
      ENVIRONMENT: ${{ steps.extractEnvAndVersion.outputs.TAG_ENV }}
      VERSION: ${{ steps.extractEnvAndVersion.outputs.TAG_VERSION }}
    steps:
      - name: Extract env and version
        id: extractEnvAndVersion
        run: |
          if [ "$DOCKER_TAG" == "" ]; then
            part1=$(echo "$GIT_TAG" | cut -d'/' -f2)
            echo "TAG_VERSION=$part1" >> $GITHUB_OUTPUT
            echo "TAG_ENV=prod" >> $GITHUB_OUTPUT
          else
            echo "TAG_VERSION=$DOCKER_TAG" >> $GITHUB_OUTPUT
            echo "TAG_ENV=$ENV" >> $GITHUB_OUTPUT
          fi

      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
