name: prod-init
on:
  workflow_call:
    inputs:
      GIT_TAG:
        type: string
      DOCKER_TAG:
        type: string
      ENVIRONMENT:
        type: string
    outputs:
      ENVIRONMENT:
        description: "Extracted environment"
        value: ${{ jobs.init.outputs.ENVIRONMENT }}
      VERSION:
        description: "Extracted version"
        value: ${{ jobs.init.outputs.VERSION }}
      HELM_BUCKET_NAME:
        description: "Helm bucket name"
        value: ${{ jobs.init.outputs.HELM_BUCKET_NAME }}
      HELM_BUCKET_URL:
        description: "Helm bucket url"
        value: ${{ jobs.init.outputs.HELM_BUCKET_URL }}
      DOCKER_REG:
        description: "Docker registry"
        value: ${{ jobs.init.outputs.DOCKER_REG }}
env:
  GIT_TAG: ${{ inputs.GIT_TAG }}
  ENV: ${{ inputs.ENVIRONMENT }}
  DOCKER_TAG: ${{ inputs.DOCKER_TAG }}

  GCLOUD_PROJECT_ID: ${{ vars.PROD_GCLOUD_PROJECT_ID }}
  DOCKER_REG_GCP: ${{ vars.DOCKER_REG_GCP }}
  DOCKER_REG_AWS: ${{ vars.DOCKER_REG_AWS }}

jobs:
  init:
    runs-on: zk-self-hosted
    outputs:
      ENVIRONMENT: ${{ steps.extractEnvAndVersion.outputs.TAG_ENV }}
      VERSION: ${{ steps.extractEnvAndVersion.outputs.TAG_VERSION }}
      HELM_BUCKET_NAME: ${{ vars.PUBLIC_HELM_S3_BUCKET }}
      HELM_BUCKET_URL: ${{ vars.PUBLIC_HELM_S3_BUCKET_URL }}
      PROJECT_ID: ${{ vars.PROD_GCLOUD_PROJECT_ID }}
    steps:
      - name: Extract env and version
        id: extractEnvAndVersion
        run: |
          GIT_TAG=${GIT_TAG#refs/*/}
          if [ "$DOCKER_TAG" == "" ]; then
            version=$(echo "$GIT_TAG" | cut -d'/' -f2)
            semver_pattern="^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9]+)?$"
            if [[ $version =~ $semver_pattern ]]; then
              echo "TAG_VERSION=$version" >> $GITHUB_OUTPUT
              echo "TAG_ENV=prod" >> $GITHUB_OUTPUT
            else
              exit 1  # Exit with failure
              echo "invalid version tag - ${version}. Tag should follow the pattern 1.0.0-<alpha or beta (optional text))>"
            fi
          else
            echo "TAG_VERSION=$DOCKER_TAG" >> $GITHUB_OUTPUT
            echo "TAG_ENV=$ENV" >> $GITHUB_OUTPUT
          fi

      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"

      - name: Set DOCKER_REG Variable
        id: setDockerReg
        run: |
          if [ "${{ vars.DOCKER_REG_CURRENT_CLOUD }}" == "gcp" ]; then
            echo "DOCKER_REG=$DOCKER_REG_GCP/$GCLOUD_PROJECT_ID" >> $GITHUB_OUTPUT
          elif [ "${{ vars.DOCKER_REG_CURRENT_CLOUD }}" == "aws" ]; then
            echo "DOCKER_REG=$DOCKER_REG_AWS" >> $GITHUB_OUTPUT
          fi
          echo "$DOCKER_REG"